### ISSUE TITLE
Add README to project

### ISSUE THREAD

**Issue by matthewfeickert** [ptemplem/MINERvA-workflow#1]
Now that you have a GitHub repository, it would be great for it to have a `README.md` that gives a short summary of what people would need to know to get started using it. You can also link to your [IRIS-HEP Fellow page](https://iris-hep.org/fellows/ptemplem.html) in it.

As an exercise, make a new branch and then open up a PR that will address this Issue. :+1:

**Comment by ptemplem** [comment]
PR has been created.
